# fly.toml app configuration file generated for langflow-snowy-star-1405 on 2025-05-29T19:20:50-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'langflow-snowy-star-1405'
primary_region = 'bos'

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "7860"
  LANGFLOW_HOST = "0.0.0.0"
  LANGFLOW_PORT = "7860"

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = "tcp"
  internal_port = 7860
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
